### ISSUE TITLE
search operation returning `undefined` value in `SPAWN_NODE` message

### ISSUE THREAD

**Issue by kotAPI** [kotAPI/SVGPlayground#1]
Just tested out the `search operation` it's spawning a new node, I guess maybe just selecting it if the element is found would look good

```
SPAWN_NODE 
{idx: 4, val: undefined}
idx:4
val:undefined
```

**Comment by chrzrdx** [comment]
Commit ae2e339bfc1144ed92a50d18683670d8704bfacd fixes this.

**Comment by kotAPI** [comment]
kool
